### ISSUE TITLE
Python and ont-tombo version conflicts

### ISSUE THREAD

**Issue by rayljc** [pepebonet/DeepMP#20]
Hello Pepe,

I was unable to install ont-tombo with the installation guide in README. Specifically, it seems python 3.8 is incompatible with [ont-tombo](https://pypi.org/project/ont-tombo/).

Steps to reproduce and error logs:
` conda create --name deepmp_2021 python=3.8`
`conda activate deepmp_2021`
`pip install -e .` (optional)
`pip install ont-tombo`
Then I got error `ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/var/folders/33/p9lc85_n1wj2xd2m11xj923h0000gn/T/tmp5eiuqzfn/output.json'`

With `conda install -c bioconda ont-tombo` I got `UnsatisfiableError: The following specifications were found to be incompatible with the existing python installation in your environment: Specifications: - ont-tombo -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
`

Is there anything I should do to resolve this issue? Thank you!

Ray

**Comment by mandichen** [comment]
Hi Ray,

It is recommended to install DeepMP before installing tombo. Please make sure to run `pip install -e .` inside DeepMP main folder before the next step.

We use `pip install ont-tombo` instead of conda, which will get around the version conflict problem. According to [Tombo documentation ](https://github.com/nanoporetech/tombo), R is required for installing tombo via pip. Please make sure that R is installed in your environment. 

Let us know if this works for you.

Cheers,
Mandi

**Comment by rayljc** [comment]
Hi Mandi,

Thanks for the reply! I followed all the steps, making sure to run `pip install -e .` and using pip to install ont-tombo. Also checked that R has already been installed in the environment. Unfortunately, same issue still exists.

I am a little bit curious why pip is preferred for this use case, since the preferred method seems to be conda, according to the official documentation: https://github.com/nanoporetech/tombo.

With the above being said, I successfully installed DeepMP with python 3.7 and conda. Please feel free to close this issue if there is no additional input from your side. Thank you!

Cheers,
Ray

**Comment by mandichen** [comment]
Hi Ray,

Thanks for the updates.

Tombo is used for the resquiggle procedure. Any tombo version with a resquiggle algorithm can do the job. 
Since resquiggle is a stand-alone step, it can be separated from running DeepMP functions. That it to say, tombo is not required for installing DeepMP. 

We tested the installation several times with `pip install ont-tombo` (on Linux os) and didn't encounter any issues, therefore we kept the workable version in the README. We haven't tried Python 3.7 yet, glad to know that also works. :)

Cheers,
Mandi
